"""
detector.py - Heuristic AI Content Detector Engine
===================================================

This module provides text analysis logic to estimate the likelihood that a block
of text was generated by an AI language model (e.g., ChatGPT, Claude) versus written by a human.

COLLEGE VIVA EXPLANATION SUMMARY:
--------------------------------
AI text generators tend to exhibit recognizable statistical patterns in their writing:
1. Sentence Consistency: AI tends to write sentences of relatively uniform length (low standard deviation).
2. Transition Words & Formal Language: AI frequently uses formal markers like 'Furthermore', 'Moreover', etc.
3. Vocabulary Diversity & Predictability: AI uses balanced, predictable vocabulary with moderate diversity.
4. Repetition & Structural Regularity: AI often uses structured sentence templates and repeated phrase patterns.

This detector measures these features using Python's standard `re`, `math`, and `collections` libraries
and combines them into a normalized AI-Likelihood percentage score (0-100%).
"""

import re
import math
from collections import Counter

class AIContentDetector:
    """
    Analyzes text across 5 key statistical dimensions to calculate AI likelihood.
    """
    
    FORMAL_TRANSITIONS = [
        "furthermore", "moreover", "additionally", "in conclusion", "therefore",
        "consequently", "nonetheless", "it is important to note", "in summary",
        "as a result", "on the other hand", "notably", "significantly", "thus",
        "hence", "in addition", "it should be noted", "to summarize", "overall",
        "ultimately", "crucially", "indeed", "similarly", "conversely"
    ]

    def __init__(self):
        pass

    def analyze(self, text: str) -> dict:
        """
        Main entry point for analyzing text. Returns detailed metric scores,
        qualitative explanations, overall AI-likelihood, and human-like score.
        """
        # Clean text and extract words and sentences
        words = re.findall(r'\b[a-zA-Z0-9\'-]+\b', text.lower())
        word_count = len(words)
        
        # Split text into sentences using punctuation markers
        sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
        sentence_count = len(sentences)
        
        # Word count validation flag (< 50 words)
        is_short = word_count < 50

        if word_count == 0 or sentence_count == 0:
            return {
                "ai_percentage": 0,
                "human_percentage": 100,
                "label": "Low AI likelihood",
                "word_count": word_count,
                "sentence_count": sentence_count,
                "is_short": True,
                "warning": "Please enter at least 50 words for a more meaningful analysis.",
                "analysis": ["Insufficient text provided to perform statistical analysis."],
                "feature_scores": {
                    "Sentence Consistency": 0,
                    "Vocabulary Diversity": 0,
                    "Repetition": 0,
                    "Formal Language": 0,
                    "Predictability": 0
                },
                "disclaimer": "AI likelihood is an estimate based on text patterns and should not be treated as definitive proof of AI generation."
            }

        # --- FEATURE 1: Sentence Length & Consistency ---
        # AI models generate text with consistent, uniform sentence lengths (low variation).
        sentence_lengths = [len(re.findall(r'\b[a-zA-Z0-9\'-]+\b', s)) for s in sentences if len(s) > 0]
        avg_sentence_length = sum(sentence_lengths) / max(len(sentence_lengths), 1)
        
        if len(sentence_lengths) > 1:
            variance = sum((l - avg_sentence_length) ** 2 for l in sentence_lengths) / len(sentence_lengths)
            std_dev = math.sqrt(variance)
            # Coefficient of Variation (CV) = std_dev / mean. Low CV indicates high consistency.
            cv = std_dev / (avg_sentence_length + 1e-5)
            # High consistency score means CV is small (uniform sentence length)
            sentence_consistency_score = min(100, max(0, int((1.0 - min(cv, 1.0)) * 100)))
        else:
            sentence_consistency_score = 50

        # --- FEATURE 2: Vocabulary Diversity ---
        # Uses Root Type-Token Ratio (RTTR = Unique Words / sqrt(Total Words)).
        # AI text typically maintains a moderate-to-high, balanced RTTR (~3.5 to 5.5).
        unique_words = set(words)
        rttr = len(unique_words) / math.sqrt(max(word_count, 1))
        # Optimal AI RTTR band is around 3.5 - 5.5; deviate values mean lower AI score
        if rttr < 2.5:
            vocab_diversity_score = 40  # Extremely repetitive (human or low quality)
        elif 3.2 <= rttr <= 5.8:
            vocab_diversity_score = min(100, int(70 + (1.0 - abs(rttr - 4.5) / 1.3) * 30))
        else:
            vocab_diversity_score = 50

        # --- FEATURE 3: Word & Phrase Repetition ---
        # Evaluates n-gram repetition (bigrams and trigrams).
        bigrams = [f"{words[i]} {words[i+1]}" for i in range(len(words)-1)]
        trigrams = [f"{words[i]} {words[i+1]} {words[i+2]}" for i in range(len(words)-2)]
        
        bigram_counts = Counter(bigrams)
        trigram_counts = Counter(trigrams)
        
        repeated_bigrams = sum(count - 1 for count in bigram_counts.values() if count > 1)
        repeated_trigrams = sum(count - 1 for count in trigram_counts.values() if count > 1)
        
        repetition_density = (repeated_bigrams + repeated_trigrams * 2) / max(word_count, 1)
        # Moderate repetition is typical in AI structured writing
        repetition_score = min(100, max(0, int(min(repetition_density * 400, 100))))

        # --- FEATURE 4: Formal Transition & Structured Language ---
        # AI frequently uses formal conjunctions and transition words.
        lower_text = text.lower()
        formal_count = 0
        found_transitions = []
        
        for transition in self.FORMAL_TRANSITIONS:
            # Check for exact word or phrase boundary match
            pattern = r'\b' + re.escape(transition) + r'\b'
            matches = len(re.findall(pattern, lower_text))
            if matches > 0:
                formal_count += matches
                found_transitions.append(transition.capitalize())

        # Density per 100 words
        formal_density = (formal_count / max(word_count, 1)) * 100
        # 1.5+ transitions per 100 words indicates heavy AI structure
        formal_language_score = min(100, max(0, int(min(formal_density * 45, 100))))
        if formal_count > 0 and formal_language_score < 40:
            formal_language_score = min(100, 40 + formal_count * 12)

        # --- FEATURE 5: Overall Text Predictability & Regularity ---
        # Measures word length variance and structural rhythm.
        word_lengths = [len(w) for w in words]
        avg_word_len = sum(word_lengths) / max(len(word_lengths), 1)
        
        # AI writing exhibits consistent word length spread (avg word len around 4.5-5.8 with balanced variance)
        predictability_score = min(100, max(0, int(
            (sentence_consistency_score * 0.4) + (vocab_diversity_score * 0.3) + (formal_language_score * 0.3)
        )))

        # --- COMPOSITE AI LIKELIHOOD SCORE CALCULATION ---
        # Weighted average of individual feature scores
        weights = {
            "sentence_consistency": 0.25,
            "vocab_diversity": 0.20,
            "repetition": 0.15,
            "formal_language": 0.25,
            "predictability": 0.15
        }
        
        raw_score = (
            sentence_consistency_score * weights["sentence_consistency"] +
            vocab_diversity_score * weights["vocab_diversity"] +
            repetition_score * weights["repetition"] +
            formal_language_score * weights["formal_language"] +
            predictability_score * weights["predictability"]
        )

        ai_percentage = int(min(99, max(5, round(raw_score))))
        human_percentage = 100 - ai_percentage

        # Determine label classification
        if ai_percentage < 35:
            label = "Low AI likelihood"
        elif ai_percentage <= 65:
            label = "Moderate AI likelihood"
        else:
            label = "High AI likelihood"

        # Generate qualitative analysis insights
        insights = []
        if sentence_consistency_score > 65:
            insights.append("Sentence structure and length are highly consistent.")
        else:
            insights.append("Sentence length varies naturally across paragraphs.")

        if formal_count > 0:
            sample_trans = ", ".join(list(set(found_transitions))[:3])
            insights.append(f"Formal transition words are used frequently (e.g., {sample_trans}).")
        else:
            insights.append("Minimal use of formal transition words detected.")

        if vocab_diversity_score > 60:
            insights.append("Vocabulary pattern is relatively predictable.")
        else:
            insights.append("Vocabulary distribution shows natural human variability.")

        if repetition_score > 50:
            insights.append("Some repeated phrasing was detected.")
        else:
            insights.append("Phrase repetition remains low.")

        return {
            "ai_percentage": ai_percentage,
            "human_percentage": human_percentage,
            "label": label,
            "word_count": word_count,
            "sentence_count": sentence_count,
            "is_short": is_short,
            "warning": "Please enter at least 50 words for a more meaningful analysis." if is_short else None,
            "analysis": insights,
            "feature_scores": {
                "Sentence Consistency": sentence_consistency_score,
                "Vocabulary Diversity": vocab_diversity_score,
                "Repetition": repetition_score,
                "Formal Language": formal_language_score,
                "Predictability": predictability_score
            },
            "disclaimer": "AI likelihood is an estimate based on text patterns and should not be treated as definitive proof of AI generation."
        }
